/**
 * `/init` turn runner extracted from app.tsx.
 *
 * Drives a single agent turn whose prompt is generated by `buildInitPrompt`
 * — typically asking the model to scan the repo and write KIMI.md. After
 * a successful turn, refreshes the system-prompt prefix so future turns
 * see the new KIMI.md.
 *
 * The deps bag mirrors the in-component closure that previously held this
 * logic. Identical behavior to the prior `runInit` useCallback.
 */
import React from "react";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { runAgentTurn, AgentLoopError } from "../agent/loop.js";
import { ALL_TOOLS, type ToolExecutor, type PermissionAsker } from "../tools/executor.js";
import { buildSessionPrefix, buildSystemPrompt } from "../agent/system-prompt.js";
import { sanitizeString } from "../agent/messages.js";
import type { ChatMessage, Usage } from "../agent/messages.js";
import type { GatewayMeta } from "../agent/client.js";
import type { ToolSpec, ToolRender } from "../tools/registry.js";
import type { Mode } from "../mode.js";
import { classifyIntent } from "../intent/classify.js";
import type { ReasoningEffort } from "../config.js";
import type { TurnPhase } from "../ui/status.js";
import type { DailyUsage } from "../usage-tracker.js";
import {
  KimiApiError,
  humanizeCloudflareError,
} from "../util/errors.js";
import { logger } from "../util/logger.js";
import { recordUsage, getCostReport } from "../usage-tracker.js";
import { buildInitPrompt } from "./context-generator.js";
import type { AbortScope } from "../util/abort-scope.js";
import type { LspManager } from "../lsp/manager.js";
import type { MemoryManager } from "../memory/manager.js";
import type { ChatEvent } from "../ui/chat.js";
import type { Cfg } from "../app.js";
import type { LoopDecision } from "../ui/limit-modal.js";
import type { LoopModalState } from "../ui/use-modal-host.js";
import { gatewayFromConfig, gatewayUsageLookupFromConfig, mkAssistantId, trackRecentFile } from "../ui/app-helpers.js";

type SetEvents = React.Dispatch<React.SetStateAction<ChatEvent[]>>;

export interface RunInitDeps {
  // App-level
  cfg: Cfg;
  busy: boolean;
  mkKey: () => string;
  setEvents: SetEvents;

  // Turn-state setters
  setCodeMode: (v: boolean) => void;
  setTurnPhase: (v: TurnPhase) => void;
  setCurrentToolName: (v: string | null) => void;
  setLastActivityAt: (v: number) => void;
  setUsage: React.Dispatch<React.SetStateAction<Usage | null>>;
  setSessionUsage: React.Dispatch<React.SetStateAction<DailyUsage | null>>;
  setKimiMdStale: (v: boolean) => void;
  setLoopModal: (v: LoopModalState | null) => void;

  // Turn-lifecycle hooks
  beginTurn: () => void;
  endTurn: () => void;
  ensureSessionId: () => string;
  onIterationEnd: (messages: ChatMessage[], signal: AbortSignal) => Promise<ChatMessage[]>;
  updateAssistant: (id: number, patch: (e: { text: string; reasoning: string; streaming: boolean }) => Partial<{ text: string; reasoning: string; streaming: boolean }>) => void;
  updateTool: (id: string, patch: Partial<Extract<ChatEvent, { kind: "tool" }>>) => void;
  updateGatewayMeta: (meta: GatewayMeta) => void;
  askForPermission: (req: Parameters<PermissionAsker>[0], opts: { promptOnBlockedBash: boolean }) => ReturnType<PermissionAsker>;
  clearPermissionResolveRef: () => void;

  // Refs
  messagesRef: React.MutableRefObject<ChatMessage[]>;
  sessionScopeRef: React.MutableRefObject<AbortScope>;
  activeScopeRef: React.MutableRefObject<AbortScope | null>;
  mcpToolsRef: React.MutableRefObject<ToolSpec[]>;
  lspToolsRef: React.MutableRefObject<ToolSpec[]>;
  executorRef: React.MutableRefObject<ToolExecutor>;
  effortRef: React.MutableRefObject<ReasoningEffort>;
  memoryManagerRef: React.MutableRefObject<MemoryManager | null>;
  pendingToolCallsRef: React.MutableRefObject<Map<string, string>>;
  recentFilesRef: React.MutableRefObject<Map<string, number>>;
  usageRef: React.MutableRefObject<Usage | null>;
  activeAsstIdRef: React.MutableRefObject<number | null>;
  gatewayMetaRef: React.MutableRefObject<GatewayMeta | null>;
  kimiMdStaleNudgedRef: React.MutableRefObject<boolean>;
  lspManagerRef: React.MutableRefObject<LspManager>;
  modeRef: React.MutableRefObject<Mode>;
  cacheStableRef: React.MutableRefObject<boolean>;
  lastApiErrorRef: React.MutableRefObject<{ httpStatus?: number; code?: number; message: string } | null>;
  limitResolveRef: React.MutableRefObject<unknown>;
  loopResolveRef: React.MutableRefObject<((d: LoopDecision) => void) | null>;
}

export async function runInit(deps: RunInitDeps): Promise<void> {
  const {
    cfg, busy, mkKey, setEvents,
    setCodeMode, setTurnPhase, setCurrentToolName, setLastActivityAt,
    setUsage, setSessionUsage,
    setKimiMdStale, setLoopModal,
    beginTurn, endTurn, ensureSessionId, onIterationEnd,
    updateAssistant, updateTool, updateGatewayMeta,
    askForPermission, clearPermissionResolveRef,
    messagesRef, sessionScopeRef, activeScopeRef,
    mcpToolsRef, lspToolsRef, executorRef, effortRef, memoryManagerRef,
    pendingToolCallsRef, recentFilesRef, usageRef, activeAsstIdRef,
    gatewayMetaRef, kimiMdStaleNudgedRef, lspManagerRef, modeRef,
    cacheStableRef, lastApiErrorRef, limitResolveRef, loopResolveRef,
  } = deps;

  if (busy) {
    setEvents((e) => [...e, { kind: "info", key: mkKey(), text: "can't /init while model is running" }]);
    return;
  }
  const cwd = process.cwd();
  const { prompt, targetFilename, isRefresh } = buildInitPrompt(cwd);

  setEvents((e) => [
    ...e,
    { kind: "user", key: mkKey(), text: isRefresh ? `/init (refreshing ${targetFilename})` : "/init" },
  ]);
  messagesRef.current.push({ role: "user", content: sanitizeString(prompt) });
  beginTurn();
  const turnScope = sessionScopeRef.current.createChild();
  activeScopeRef.current = turnScope;

  const initClassification = classifyIntent(prompt);
  const initEffortForTier: Record<string, ReasoningEffort> = {
    light: "low",
    medium: "medium",
    heavy: "high",
  };
  const initReasoningEffort = initEffortForTier[initClassification.tier] ?? effortRef.current;
  const effectiveCodeMode = initClassification.tier === "heavy";
  setCodeMode(effectiveCodeMode);

  try {
    await runAgentTurn({
      accountId: cfg.accountId,
      apiToken: cfg.apiToken,
      model: cfg.model,
      gateway: gatewayFromConfig(cfg),
      messages: messagesRef.current,
      tools: [...ALL_TOOLS, ...mcpToolsRef.current, ...lspToolsRef.current],
      executor: executorRef.current,
      cwd,
      signal: turnScope.signal,
      reasoningEffort: initReasoningEffort,
      intentClassification: initClassification,
      coauthor:
        cfg.coauthor !== false
          ? { name: cfg.coauthorName || "kimiflare", email: cfg.coauthorEmail || "kimiflare@proton.me" }
          : undefined,
      sessionId: ensureSessionId(),
      memoryManager: memoryManagerRef.current,
      githubToken: cfg.githubOAuthToken,
      codeMode: effectiveCodeMode,
      providerKeys: cfg.providerKeys,
      providerKeyAliases: cfg.providerKeyAliases,
      unifiedBilling: cfg.unifiedBilling,
      shell: cfg.shell,
      onIterationEnd,
      onFileChange: (path, content) => {
        if (content) {
          lspManagerRef.current.notifyChange(path, content);
        } else {
          // For edit tool, read the file and notify with full content
          void import("node:fs/promises").then(({ readFile }) =>
            readFile(path, "utf8")
              .then((c) => lspManagerRef.current.notifyChange(path, c))
              .catch(() => {}),
          );
        }
      },
      callbacks: {
        onAssistantStart: () => {
          const id = mkAssistantId();
          activeAsstIdRef.current = id;
          setEvents((e) => [
            ...e,
            { kind: "assistant", key: `asst_${id}`, id, text: "", reasoning: "", streaming: true },
          ]);
        },
        onReasoningDelta: (d) => {
          const id = activeAsstIdRef.current;
          if (id !== null) updateAssistant(id, (e) => ({ reasoning: e.reasoning + d }));
        },
        onTextDelta: (d) => {
          const id = activeAsstIdRef.current;
          if (id !== null) updateAssistant(id, (e) => ({ text: e.text + d }));
        },
        onAssistantFinal: () => {
          const id = activeAsstIdRef.current;
          if (id !== null) updateAssistant(id, () => ({ streaming: false }));
        },
        onToolCallFinalized: (call) => {
          pendingToolCallsRef.current.set(call.id, call.function.name);
          const spec = executorRef.current.list().find((t) => t.name === call.function.name);
          let renderMeta: ToolRender | undefined;
          let args: Record<string, unknown> = {};
          try {
            args = call.function.arguments ? JSON.parse(call.function.arguments) : {};
            renderMeta = spec?.render?.(args);
          } catch {
            /* ignore */
          }
          // Track file paths from read/edit/write/grep tools for recent-files boost
          if (typeof args.path === "string") {
            trackRecentFile(recentFilesRef, args.path);
          }
          setEvents((e) => [
            ...e,
            {
              kind: "tool",
              key: `tool_${call.id}`,
              id: call.id,
              name: call.function.name,
              args: call.function.arguments,
              status: "queued",
              render: renderMeta,
              expanded: false,
            },
          ]);
        },
        onToolWillExecute: (id: string) => {
          setTurnPhase("executing");
          setCurrentToolName(pendingToolCallsRef.current.get(id) ?? null);
          setLastActivityAt(Date.now());
          updateTool(id, { status: "running", startedAt: Date.now() });
        },
        onToolResult: (r) => {
          pendingToolCallsRef.current.delete(r.tool_call_id);
          setLastActivityAt(Date.now());
          if (pendingToolCallsRef.current.size === 0) {
            setTurnPhase("waiting");
            setCurrentToolName(null);
          }
          const isDenied = typeof r.content === "string" && r.content.startsWith("Permission denied");
          updateTool(r.tool_call_id, {
            status: isDenied ? "rejected" : r.ok ? "done" : "error",
            result: r.content,
          });
        },
        onWarning: (msg) => {
          setEvents((e) => [...e, { kind: "info", key: mkKey(), text: msg }]);
        },
        onUsage: (u) => {
          usageRef.current = u;
          setUsage(u);
        },
        onUsageFinal: (u, meta) => {
          const sid = ensureSessionId();
          void recordUsage(sid, u, gatewayUsageLookupFromConfig(cfg, meta ?? gatewayMetaRef.current), cfg?.model);
          void getCostReport(sid).then((report) => setSessionUsage(report.session));
        },
        onGatewayMeta: updateGatewayMeta,
        askPermission: (req) => askForPermission(req, { promptOnBlockedBash: true }),
        onLoopDetected: () =>
          new Promise<LoopDecision>((resolve) => {
            loopResolveRef.current = resolve;
            setLoopModal({ resolve });
          }),
        onKimiMdStale: () => {
          if (!kimiMdStaleNudgedRef.current) {
            kimiMdStaleNudgedRef.current = true;
            setKimiMdStale(true);
            setEvents((e) => [
              ...e,
              {
                kind: "info",
                key: mkKey(),
                text: "Project context may be stale. Run /init to refresh KIMI.md based on recent changes.",
              },
            ]);
          }
        },
      },
    });

    if (existsSync(join(cwd, "KIMI.md"))) {
      if (cacheStableRef.current) {
        messagesRef.current[1] = {
          role: "system",
          content: buildSessionPrefix({
            cwd,
            tools: [...ALL_TOOLS, ...mcpToolsRef.current, ...lspToolsRef.current],
            model: cfg.model,
            mode: modeRef.current,
          }),
        };
      } else {
        messagesRef.current[0] = {
          role: "system",
          content: buildSystemPrompt({
            cwd,
            tools: [...ALL_TOOLS, ...mcpToolsRef.current, ...lspToolsRef.current],
            model: cfg.model,
            mode: modeRef.current,
          }),
        };
      }
      setEvents((e) => [
        ...e,
        { kind: "info", key: mkKey(), text: "KIMI.md generated; context loaded for future turns" },
      ]);
      // Record refresh so drift detection knows this snapshot is current
      void memoryManagerRef.current?.recordKimiMdRefresh(cwd, ensureSessionId());
      setKimiMdStale(false);
      kimiMdStaleNudgedRef.current = false;
    }
  } catch (e) {
    if ((e as Error).name === "AbortError") {
      for (const [tcId, tcName] of pendingToolCallsRef.current) {
        messagesRef.current.push({
          role: "tool",
          tool_call_id: tcId,
          content: "(stopped)",
          name: tcName,
        });
      }
      setEvents((evts) =>
        evts.map((ev) =>
          ev.kind === "tool" && ev.status === "running"
            ? { ...ev, status: "error" as const, result: "(stopped)" }
            : ev,
        ),
      );
    } else if (e instanceof AgentLoopError) {
      setEvents((es) => [
        ...es,
        {
          kind: "error",
          key: mkKey(),
          text:
            "/init stopped: the agent kept repeating the same tool calls and couldn't finish writing KIMI.md. " +
            "Try /init again — if it loops in the same place, the repo may be too large for a single pass; " +
            "you can write KIMI.md manually or scope it by deleting noisy paths from your .gitignore-style ignore list.",
        },
      ]);
    } else if (
      e instanceof KimiApiError &&
      (e.httpStatus === 429 || e.code === 3040 || (e.httpStatus !== undefined && e.httpStatus >= 500))
    ) {
      const err = { httpStatus: e.httpStatus, code: e.code, message: humanizeCloudflareError(e) };
      lastApiErrorRef.current = err;
      setEvents((es) => [...es, { kind: "api_error", key: mkKey(), ...err }]);
    } else {
      const displayText =
        e instanceof KimiApiError ? humanizeCloudflareError(e) : `init failed: ${(e as Error).message}`;
      setEvents((es) => [...es, { kind: "error", key: mkKey(), text: displayText }]);
    }
  } finally {
    logger.info("runInit:finally");
    setCodeMode(false);
    const asstId = activeAsstIdRef.current;
    if (asstId !== null) updateAssistant(asstId, () => ({ streaming: false }));
    endTurn();
    activeAsstIdRef.current = null;
    activeScopeRef.current = null;
    clearPermissionResolveRef();
    limitResolveRef.current = null;
    loopResolveRef.current = null;
    setLoopModal(null);
    pendingToolCallsRef.current.clear();
  }
}
